[package]
name = "soundcore-control"
version = "0.2.0"
edition = "2024"
rust-version = "1.85"
description = "A native Linux controller for Soundcore earbuds and headphones"
license = "GPL-3.0-or-later"
repository = "https://github.com/d7omdev/soundcore-control"
homepage = "https://github.com/d7omdev/soundcore-control"
readme = "README.md"
keywords = ["soundcore", "bluetooth", "earbuds", "linux", "audio"]
categories = ["gui", "multimedia::audio"]
publish = false

[dependencies]
anyhow = "1"
bluer = { version = "0.17.4", features = ["bluetoothd"] }
dirs = "6"
futures = "0.3"
eframe = { version = "0.33.3", default-features = false, features = [
  "default_fonts",
  "glow",
  "wayland",
  "x11",
] }
i18n-embed = { version = "0.16", features = ["desktop-requester"] }
image = { version = "0.25", default-features = false, features = ["png"] }
ksni = "0.3.5"
libc = "0.2"
macaddr = "1"
notify-rust = "4"
openscq30-i18n = { git = "https://github.com/Oppzippy/OpenSCQ30.git", rev = "08b28dd8ce8c9f91c3ef44ad25c9d5f3491a2aa0" }
openscq30-lib = { git = "https://github.com/Oppzippy/OpenSCQ30.git", rev = "08b28dd8ce8c9f91c3ef44ad25c9d5f3491a2aa0" }
rust-embed = "8"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "sync"] }
toml = "0.5"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dev-dependencies]
pretty_assertions = "1"

[profile.release]
lto = "thin"
strip = true
